import "@/styles/reset.css";
import "@/styles/globals.css";
import { alata } from "@/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={alata.className}>{children}</body>
    </html>
  );
}
