import "@/styles/reset.css";
import "@/styles/globals.css";
import { Alata, Josefin_Sans } from "next/font/google";

const alata = Alata({ subsets: ["latin"], weight: ["400"] });
export const josefin = Josefin_Sans({ subsets: ["latin"], weight: ["300"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={alata.className}>{children}</body>
    </html>
  );
}
